### ISSUE TITLE
Error clicking on new entry after installing this plugin

### ISSUE THREAD

**Issue by karan-saluja** [iNalgiev/craft-webtexttool#2]
I can not create new entries. Whenever I clicked on new entry button, craft would throw an error. I'm attaching a screenshot for your reference. I have installed the latest versions of both craft and Textmetrics.
![unnamed](https://user-images.githubusercontent.com/28668444/63153915-1632cc80-c02d-11e9-9dc6-ed6a3ff9cb82.png)

**Comment by iNalgiev** [comment]
Hi @karan-saluja, 

Thank you for reporting the issue. 

We've added the issue to the list. We'll keep you updated when the issue has been fixed.

**Comment by iNalgiev** [comment]
Hi @karan-saluja,

An update (v1.1.1) has been released which hopefully fixes the issue.

**Comment by karan-saluja** [comment]
Hi @iNalgiev 
Thanks a lot :) 
It is working perfectly now.
